In [5]:
import numpy as np
print(np.__version__)

1.26.4


In [6]:
arry = np.array([1,2,3,4,'a',6])

In [8]:
arry

array(['1', '2', '3', '4', 'a', '6'], dtype='<U11')

In [9]:
type(arry)

numpy.ndarray

In [10]:
list1=[1,2,3,4]
array1 = np.array(list1)

In [11]:
type(list1)

list

In [13]:
type(array1)

numpy.ndarray

In [14]:
list2 = [10,11,'a',12]
array2 = np.array(list2)

In [15]:
print(f"Adding two lists {list1} and {list2} together: {list1 + list2}")

Adding two lists [1, 2, 3, 4] and [10, 11, 'a', 12] together: [1, 2, 3, 4, 10, 11, 'a', 12]


In [16]:
list12 = [1,2,3]
list23 = [3,4,5,6,7,8,9,0]
list12 + list23

[1, 2, 3, 3, 4, 5, 6, 7, 8, 9, 0]

In [21]:
array1 = np.array([1,2,3,5])
array2 = np.array([4,6,7,8])
array1 + array2

array([ 5,  8, 10, 13])

In [22]:
print(f"Adding two numpy arrays {array1} and {array2} together: {array1 + array2}")

Adding two numpy arrays [1 2 3 5] and [4 6 7 8] together: [ 5  8 10 13]


In [28]:
np.random.seed(25) #seed for reproductibility

x1 = np.random.randint(11, size=6, dtype='int16') #One-dimensional array
x2 = np.random.randint(11, size=(5, 4)) #Two-dimesional array
x3 = np.random.randint(11, size=(3, 2, 5)) #Three-dimesional array

In [29]:
print(x1)
print("-" * 30)
print(x2)
print("-" * 30)
print(x3)

[ 4  0  1 10  0  9]
------------------------------
[[6 7 2 8]
 [4 9 4 5]
 [1 7 3 8]
 [7 3 4 3]
 [1 6 0 9]]
------------------------------
[[[ 0  2  5  4  9]
  [ 0 10 10  1  6]]

 [[ 1  2  4  2  5]
  [ 8  0  6  4  2]]

 [[ 5  9  9  6  0]
  [ 2 10  4  3 10]]]


In [31]:
print("The attributes of x3 are::\n")
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

The attributes of x3 are::

x3 ndim:  3
x3 shape: (3, 2, 5)
x3 size: 30


In [32]:
print("The attributes of x2 are::\n")
print("x3 ndim: ", x2.ndim)
print("x3 shape:", x2.shape)
print("x3 size:", x2.size)

The attributes of x2 are::

x3 ndim:  2
x3 shape: (5, 4)
x3 size: 20


In [33]:
print("dtype:", x3.dtype)

dtype: int32


In [34]:
x1.dtype

dtype('int16')

In [35]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 120 bytes


In [36]:
x1

array([ 4,  0,  1, 10,  0,  9], dtype=int16)

In [37]:
x1[4]

0

In [38]:
x1[-1]

9

In [39]:
x1[-2]

0

In [40]:
x2

array([[6, 7, 2, 8],
       [4, 9, 4, 5],
       [1, 7, 3, 8],
       [7, 3, 4, 3],
       [1, 6, 0, 9]])

In [41]:
x2[0][0]

6

In [42]:
x2[0, 0]

6

In [43]:
x2[2, 0]

1

In [45]:
x2[2, -1]

8

In [46]:
x2[0, 0] = 10
x2

array([[10,  7,  2,  8],
       [ 4,  9,  4,  5],
       [ 1,  7,  3,  8],
       [ 7,  3,  4,  3],
       [ 1,  6,  0,  9]])

In [47]:
x1

array([ 4,  0,  1, 10,  0,  9], dtype=int16)

In [48]:
x1[0] = 3.14159
x1

array([ 3,  0,  1, 10,  0,  9], dtype=int16)

In [50]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
x[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
x[10:]

array([10, 11, 12, 13, 14, 15])

In [55]:
x[5:10]

array([5, 6, 7, 8, 9])

In [56]:
x[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [57]:
x[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [58]:
#arr = np.arange(0,11)
#print("Array:", arr)
#print('_' *70)
#print("Element at 7th index is:", arr[7])
#print('_' *70)
# print("Elements from 3rd to 5th index are:", arr[3:6])
# print('-' *70)
# print("Elements up to 4th index are:", arr[:4])
# print('-' *70)
# print("Elements from last backwards are:", arr[-1::-1])
# print('-' *70)
# print("3 Elements from last backwards are:", arr[-1:-6:-2])
# print('-' *70)
# print('-' *70)

# arr2 = np.arange(0,21,2)
# print("New array:",arr2)
# print("Elements at 2nd, 4th, and 9th index are:", arr2[[2,4,9]]) # Pass a list as a index to subset


In [59]:
x2

array([[10,  7,  2,  8],
       [ 4,  9,  4,  5],
       [ 1,  7,  3,  8],
       [ 7,  3,  4,  3],
       [ 1,  6,  0,  9]])

In [60]:
x2[:2, :3]

array([[10,  7,  2],
       [ 4,  9,  4]])

In [61]:
x2[:3, ::2]

array([[10,  2],
       [ 4,  4],
       [ 1,  3]])

In [62]:
np.random.randint(10, 100, 15)

array([27, 24, 93, 47, 97, 60, 61, 24, 81, 72, 25, 24, 86, 49, 98])

In [63]:
mat = np.random.randint(10, 100, 15).reshape(3, 5)
print("Matrix of random 2-digit numbers\n",mat)

Matrix of random 2-digit numbers
 [[56 63 39 23 56]
 [63 72 77 12 54]
 [54 73 55 34 19]]


In [65]:
print("Double bracket indexing\n")
print("Element in row index 1 and column index 2:", mat[1][2])

print("\nSingle bracket with comma indexing\n")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n")

print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:, 3])

Double bracket indexing

Element in row index 1 and column index 2: 77

Single bracket with comma indexing

Element in row index 1 and column index 2: 77

Row or column extract

Entire row at index 2: [54 73 55 34 19]
Entire column at index 3: [23 12 34]


In [66]:
x2

array([[10,  7,  2,  8],
       [ 4,  9,  4,  5],
       [ 1,  7,  3,  8],
       [ 7,  3,  4,  3],
       [ 1,  6,  0,  9]])

In [67]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[10  7]
 [ 4  9]]


In [68]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  7]
 [ 4  9]]


In [69]:
print(x2)

[[10  7  2  8]
 [ 4  9  4  5]
 [ 1  7  3  8]
 [ 7  3  4  3]
 [ 1  6  0  9]]


In [73]:
list2 = [10,11,12,13]
array = np.array(list2)

In [74]:
print(array1)
print('_' *30)
print(array2)

[1 2 3 5]
______________________________
[4 6 7 8]


In [75]:
print("array2 multiplated by array1:", array1*array2)
print('_' *70)
print("array2 divided by array1:", array2/array1)
print('_' *70)
print("array2 raised to the power of array1:", array2**array1)

array2 multiplated by array1: [ 4 12 21 40]
______________________________________________________________________
array2 divided by array1: [4.         3.         2.33333333 1.6       ]
______________________________________________________________________
array2 raised to the power of array1: [    4    36   343 32768]
